# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b6c018c9484dbea2576130c79a9456cb2fe4ccfc7a34b1ca8679eb417f98bd0a746679b73af1dab89d350076dca750f646fa87797b34fce5350520685a481b8

test:
  secret_key_base: 0ef02e40d2c807a7cb6d858ed1de6189df65ccf7194673d2bbefc889131a8d1e1c4bed720014d4db750139f35ff091b205e38875b9a09f8db84341906e9cb4c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
